export const routes = {
  login: "/(auth)/login",
  forgotPassword: "/(auth)/forgot-password",
  overview: "/(tabs)/overview",
  customers: "/(tabs)/customers",
  cityList: "/cities",
  add: "/(tabs)/add",
  map: "/(tabs)/map",
  management: "/(tabs)/management",
  managementCustomers: "/management/customers",
  managementProducts: "/management/products",
  managementCountries: "/management/countries",
  managementCatalog: "/management/catalog",
  managementDrivers: "/management/drivers",
  managementAdmins: "/management/admins",
  managementWhatsapp: "/management/whatsapp",
  managementDriverMap: "/management/driver-map",
  customerEditBase: "/customer/edit",
  settings: "/(tabs)/settings",
  adminUsers: "/admin/users",
  adminCreateUser: "/admin/create-user",
} as const;
