export const routes = {
  login: "/(auth)/login",
  forgotPassword: "/(auth)/forgot-password",
  overview: "/(tabs)/overview",
  cities: "/(tabs)/cities",
  cityList: "/cities/index",
  add: "/(tabs)/add",
  map: "/(tabs)/map",
  management: "/(tabs)/management",
  managementProducts: "/management/products",
  managementCountries: "/management/countries",
  managementRegions: "/management/regions",
  managementCatalog: "/management/catalog",
  settings: "/(tabs)/settings",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminCreateUser: "/admin/create-user",
} as const;
